language: java
jdk:
- openjdk7

cache:
  directories:
  - $HOME/.m2

script:
  - mvn -Pretail -f ./parent/pom.xml verify

after_success:
  # Skip deployment on Pull Request
  - if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then exit(0); fi
  # Skip deployment if branch is not master
  - if [ "${TRAVIS_BRANCH}" != "false" ]; then exit(0); fi
  # Deployment steps
  - set -e
  # extract version from repo pom
  - VERSION=$(basename releng/de.marw.cdt.cmake-repo/target/cmake4eclipse-*.zip| sed -r -n 's/.+-([0-9]+(\.[0-9]+)*).zip$/\1/p')
  # upload p2 repo zip to bintray as a new version
  # Required env vars for deploy:
  #   BINTRAY_USER:
  #   BINTRAY_API_KEY
  #   BINTRAY_REPO
  - curl -f -T releng/de.marw.cdt.cmake-repo/target/cmake4eclipse*${VERSION}.zip -u${BINTRAY_USER}:${BINTRAY_API_KEY} https://api.bintray.com/content/${BINTRAY_USER}/${BINTRAY_REPO}/${VERSION}/
