env:
  global:
  - secure: WqLrhcL9sL1Z+yx0HeH10ev+nbf/JhUlBFkSRdpp88DFaf6E13vAcIYrzpoSgv+UFzLtARJLeb+PrtAZVYQMpGiuZ8PfmrZXTWlq0Zw+kycJZQXKT26vMKNCcfinekSYk5HgcoYlaiYcq9xq9n7F/SyJ+Aoqmpw30DSSWcfdp/8=
  - secure: nem1vmNRc3BUgguMPSP/wdtNQbLlYwyLV0V8nnx3P7grJr/BPRdOR23rD2SZN2sSOalB1WXi3U+KYrnDa2ezMyAneXfdIwc3AZKwlxWl2/c/pVkg4fotzoquJGIaY4mVMfEXH4PUiGuOw4lbzOI+v5NAt1Qy0uIcaHeTZNqNHFM=

language: java
jdk:
- openjdk8

cache:
  directories:
  - $HOME/.m2

script:
  - mvn -Prelease -f ./parent/pom.xml verify

after_success:
  # Skip deployment on Pull Request
  # extract persion from repo pom
  - echo "TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST}"
  - VERSION=$(basename releng/de.marw.cdt.cmake-repo/target/cmake4eclipse-*.zip| sed -r -n 's/.+-([0-9]+(\.[0-9]+)*).zip$/\1/p')
  - if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then exit 0; fi
  # Skip deployment if branch is not master
  - echo "TRAVIS_BRANCH=${TRAVIS_BRANCH}"
  - if [ "${TRAVIS_BRANCH}" != "master" ]; then exit 0; fi
  # Deployment steps
  - set -e
  # extract persion from repo pom
  - VERSION=$(basename releng/de.marw.cdt.cmake-repo/target/cmake4eclipse-*.zip| sed -r -n 's/.+-([0-9]+(\.[0-9]+)*).zip$/\1/p')
  # upload p2 repo zip to bintray as a new version
  - curl -f -T releng/de.marw.cdt.cmake-repo/target/cmake4eclipse*${VERSION}.zip -u${BINTRAY_USER}:${BINTRAY_API_KEY} https://api.bintray.com/content/${BINTRAY_USER}/p2-zip/cmake4eclipse/${VERSION}/
