bundleName=cmake4eclipse CDT CMake build integration UI

category.build.name=C/C++ Build
category.build.description=Command category for the C/C++ build actions
command.buildSelectedFiles.name=Build Selected File(s)
command.buildSelectedFiles.description=Builds the selected files
command.buildSelectedFiles.label=Build Selected File(s)
